### ISSUE TITLE
Drop exoskeleton

### ISSUE THREAD

**Issue by hoppula** [SC5/cerebellum#2]
Exoskeleton is currently only used for Model, Collection & Events and includes lots of unnecessary stuff that bloats the build. 

- [ ] Extract Events implementation as standalone module
- [ ] Extract AJAX & Sync parts as standalone module
- [ ] Extract Model & Collection as standalone modules, remove setter methods
- [ ] Fix tests

**Comment by hoppula** [comment]
New version with https://github.com/hoppula/vertebrae is coming soon, need to push it npm first.

**Comment by apaatsio** [comment]
exoskeleton is still in package.json

**Comment by hoppula** [comment]
@apaatsio Good catch. Fixed. Also removed axios as axios adapter is included with vertebrae.
