### ISSUE TITLE
Is this unidirectional?

### ISSUE THREAD

**Issue by staltz** [SC5/cerebellum#9]
![image](https://cloud.githubusercontent.com/assets/90512/6057885/db782776-ad2a-11e4-8603-f31314aacbdf.png)

**Comment by hoppula** [comment]
Actually it is, I just suck at drawing diagrams :) I'll replace that with a simpler version later today.

**Comment by hoppula** [comment]
![](https://camo.githubusercontent.com/79d0a9b04617f1275e820b7432d6883f00510f24/687474703a2f2f692e696d6775722e636f6d2f667578653953772e706e67)

Is this better? Store does not directly change anything in response to View change event, but sends an API request and triggers event when it's ready. Client can then act on the event and trigger route handler to render again with new data.

**Comment by staltz** [comment]
Still bidirectional (Store->View, View->Store). And what about the arrow from Store to Router in the first diagram? And the arrow from Store -> View is in the second diagram but not in the first diagram.

**Comment by hoppula** [comment]
Those events from View to Store do not actually update anything inside the Store's models/collections, they're just requests for API calls. When API calls finish you fetch the data again, so you are only ever rendering to one direction. 

Those double arrows between Store and Router in the first diagram were meant to present that route handlers fetch the data from Store, which is described in better way in second diagram. 

In the second diagram I decided to draw the arrow directly from Store to View as route handlers render the View with the data from Store as soon as all fetch requests are done.

I could move the change events handler from Store to a different module (ChangeDispatcher or something) but the functionality would still be the same. There's one path to render things and all updates go through one path to finally render again.

**Comment by staltz** [comment]
> Those events from View to Store do not actually update anything inside the Store's models/collections, they're just requests for API calls.

Anyway, data flows from View to Store. Events are data too.

>Those double arrows between Store and Router in the first diagram were meant to present that route handlers fetch the data from Store.

Router fetching from Store is not unidirectional dataflow. One way data binding is about reactivity, events, and listeners.

**Comment by hoppula** [comment]
So you do not consider any Flux implementation to be unidirectional? They also send change events from views to a dispatcher. You can argue about semantics, but if we consider Flux unidirectional, then this is unidirectional as well. By the way, good work on cycle :+1:

**Comment by staltz** [comment]
Flux's dispatcher is a big mistake, and some Flux implementations such as [reflux](https://github.com/spoike/refluxjs#differences-with-flux) have Actions listenable by Stores. If it's not listenable/reactive, then it's not actually one way data flow. If you have to fetch any data from above, then it's not one way. Think about React rendering: you never need to call rerender(), because the rendering is listening to state/props and reacts accordingly.

**Comment by hoppula** [comment]
Yeah, I agree when you put it that way. When the whole rendering path is based on routes, then it's quite hard to be 100% reactive with data updates. What would you call the data flow pattern in Cerebellum? Broken? :) It surely isn't 2-way binding in angular sense.

**Comment by staltz** [comment]
It's not broken, it seems to be an MV* architecture that works for your needs. Just seems a bit misleading to call it unidirectional data flow when that term has a clear meaning.
:+1:

**Comment by hoppula** [comment]
All right, I will remove the offending buzzword and let people judge from the diagram :) Thanks for your feedback.
